[package]
name = "rp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixedbitset = "0.5.6"
succinct = "0.5.2"
avl = "0.7.1"
binary_search_tree = "0.2.2"
elias-fano = "1.1.0"